### ISSUE TITLE
Slavic cat doesn't properly behave with fish_mode_prompt

### ISSUE THREAD

**Issue by fezboy** [yangwao/omf-theme-slavic-cat#2]
When using fish_vi_keybindings, the mode is displayed twice in the prompt, once with the fish_mode_prompt, which is run by default, and again by slavic cat
![image](https://user-images.githubusercontent.com/31973884/80045824-767fe500-84bd-11ea-88f7-47740428b3bb.png)
The slavic cat mode indicator also doesn't properly update with the modes.

**Comment by yangwao** [comment]
Wow, thank you for this! 😻

**Comment by fezboy** [comment]
Yea np man
