### ISSUE TITLE
Theme breaks with 'stderr-nocaret' and 'qmark-noglob' enabled

### ISSUE THREAD

**Issue by fcannini** [yangwao/omf-theme-slavic-cat#4]
Hello there.

`omf install slavic-cat` then cd to a directory with a git repository gives the below error.
These features are needed by [spack fish shell support](https://github.com/spack/spack/blob/develop/share/spack/setup-env.fish).

As a side-note, the **toaster** theme doesn't have this problem.
```
fatal: ambiguous argument '^/dev/null': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument '^/dev/null': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
</br>

The output of `omf doctor` is as below:
```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.20.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

TIA

**Comment by yangwao** [comment]
Is this related 
https://github.com/yangwao/omf-theme-slavic-cat/pull/5 ?

**Comment by fcannini** [comment]
Just updated `omf` and now it's working again!
